### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by origamiserviceuser**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@financial-times/o-autocomplete: 1.7.3</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-buttons: 7.7.4</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-expander: 6.2.6</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-footer: 9.2.6</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-forms: 9.4.9</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-header: 11.0.4</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-header-services: 5.3.3</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-layout: 5.3.1</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-overlay: 4.2.7</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-share: 9.0.1</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-social-follow: 1.0.3</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-stepped-progress: 4.0.6</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-teaser: 6.2.5</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-typography: 7.3.4</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>
<details><summary>@financial-times/o-video: 7.2.6</summary>

### Bug Fixes

* ensure components depend on the latest o-normalise version ([e910236](https://www.github.com/Financial-Times/origami/commit/e910236454318ce1bf198a06da7e76c0893c9142))
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-autocomplete is at https://github.com/Financial-Times/origami/releases/tag/o-autocomplete-v1.7.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-buttons is at https://github.com/Financial-Times/origami/releases/tag/o-buttons-v7.7.4 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-expander is at https://github.com/Financial-Times/origami/releases/tag/o-expander-v6.2.6 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-footer is at https://github.com/Financial-Times/origami/releases/tag/o-footer-v9.2.6 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-forms is at https://github.com/Financial-Times/origami/releases/tag/o-forms-v9.4.9 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-header-services is at https://github.com/Financial-Times/origami/releases/tag/o-header-services-v5.3.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-layout is at https://github.com/Financial-Times/origami/releases/tag/o-layout-v5.3.1 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-overlay is at https://github.com/Financial-Times/origami/releases/tag/o-overlay-v4.2.7 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-share is at https://github.com/Financial-Times/origami/releases/tag/o-share-v9.0.1 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-social-follow is at https://github.com/Financial-Times/origami/releases/tag/o-social-follow-v1.0.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-stepped-progress is at https://github.com/Financial-Times/origami/releases/tag/o-stepped-progress-v4.0.6 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-teaser is at https://github.com/Financial-Times/origami/releases/tag/o-teaser-v6.2.5 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-typography is at https://github.com/Financial-Times/origami/releases/tag/o-typography-v7.3.4 :sunflower:

**Pull request merged**
