### PR TITLE
Proposal migrate to dependabot native

### PR DESCRIPTION
**Pull request by notlee**
- Move proposal template from the "accepted" dir
- Add new proposal - Migrate to Dependabot Native

### CODE REVIEW

**Comment by notlee** [comment]
@JakeChampion it's kinda a shame to drop automerge when there's no urgency to migrate?

**Comment by JakeChampion** [comment]
> @JakeChampion it's kinda a shame to drop automerge when there's no urgency to migrate?

Happy to also block the work if that's what we want to do 👍

**Comment by JakeChampion** [comment]
Added the blocked label because this work is waiting upon us creating a GitHub Action which handles the automatic merging of dependabot pull-requests upon them passing all the tests and other GitHub Checks our projects have.

**Comment by chee** [comment]
why does this move the proposals out of the accepted directory?

i think the PRs should be trying to add a proposal _to the accepted directory_ because then when you merge it in, it is accepted.

**Comment by chee** [comment]
ah, i see it's a typo in the contributing guide :D

**Comment by JakeChampion** [comment]
I've given this a test run with polyfill-library.
Here is the commit which moves to Dependabot V2 and uses an automerge GitHub Action to merge the dependabot pull-requests only if all the other checks have succeeded on the pull-request -- https://github.com/Financial-Times/polyfill-library/commit/f50492db9ca35ffd243dbaeb7ed7a90e4e36d4c8

I think i is working well but will give it a few more days to see if any issues arise.

**Comment by chee** [comment]
i'm going to merge this in, because it is accepted. we can move it to implemented once it is finished

**Pull request merged**
