### PR TITLE
Update serve.json

### PR DESCRIPTION
**Pull request by chee**
d0 draft PRs get the previews?

### CODE REVIEW

**Comment by JakeChampion** [comment]
Drafts do get review apps, I did not expect that -- https://origami-webs-chee-patch-xi10tq.herokuapp.com/storybook/index.html?path=/story/components-o-banner--compact

This does make Storybook work! Nice!
image


It has also stopped the rest of the site from defaulting paths such as `/` to load `index.html` but that could be fine for branch previews?
image

**Comment by chee** [comment]
> It has also stopped the rest of the site from defaulting paths such as `/` to load `index.html` but that could be fine for branch previews? image


yeah, it's progress and proves everything works as long as you don't have that trailing slash on `iframe`

@JakeChampion before you closed that other PR did you go to `/storybook/` by yourself? i notice the comment you left says you went to `/storybook` but not `/storybook/` you would need to go to the url with the trailing slash yourself (because it's no longer auto-redirecting) and storybook-static is loading the javascript without a leading slash or path

**Comment by JakeChampion** [comment]
> @JakeChampion before you closed that other PR did you go to `/storybook/` by yourself? i notice the comment you left says you went to `/storybook` but not `/storybook/` you would need to go to the url with the trailing slash yourself (because it's no longer auto-redirecting) and storybook-static is loading the javascript without a leading slash or path

I can't actually remember if I did go to `/storybook/` - I'll reopen the PR and try it out

**Comment by JakeChampion** [comment]
@chee it's currently deploying the other PR to https://origami-webs-jakechampi-ybqy30.herokuapp.com/

**Pull request closed without merging**
