### PR TITLE
fix: Adds basic existence checking to most module entry points

### LINKED ISSUE #713: check for globals before using them in top-level component js
this should be just like this in the rest of the components #712

### PR DESCRIPTION
**Pull request by aendra-rininsland**
Ostensibly closes #713.

### CODE REVIEW

**Comment by aendra-rininsland** [comment]
Odd, not sure why this is failing. `document` doesn't exist on Percy? 🤷‍♀️

**Comment by JakeChampion** [comment]
> Odd, not sure why this is failing. `document` doesn't exist on Percy, maybe? 🤷‍♀️

Percy upgraded the browser versions and requires new baseline screenshots to be approved, it's nothing specific about this pull requests changes, just that this pull-request caused those Percy tests to run.

P.s. I still had Percy and browserstack acces but I have just removed myself. 
Screenshot_20220420-235205
P.p.s. this will likely mean new API keys will need to be added to polyfill-library GitHub secret

**Review by chee — APPROVED** [review]
cool

**Comment by notlee** [comment]
@JakeChampion get outa here! (thank you)

**Pull request merged**
