### PR TITLE
Add date input review proposal

### PR DESCRIPTION
**Pull request by notlee**
👋 

👉 [View the proposal here](https://github.com/Financial-Times/origami/blob/date-input-review/proposals/accepted/0000-date-input-review.md).

👇 leave comments and any more examples below

### CODE REVIEW

**Comment by notlee** [comment]
This is really a proposal to make a proposal, maybe less of a proposal and more: origami do some work. I think this is the most appropriate place still since it pertains to new date input components/patterns.

**Comment by notlee** [comment]
It should be accepted at the point we are ready to write guidelines and or identified components to build

**Comment by josh-wade-ft** [comment]
Questions:

- Is our custom one that's in Spark accessible? 
- If so, can we reuse on ft.com? 
- Is a dropdown style more accessible that a free text field, or vice versa?  

Thoughts on different types:

1. **Dropdown**- there is a case to use a dropdown style, for example when it comes to card details or any type of form that require a month or year only input.
2. **Custom picker** - as you've mentioned, there is good case for this when the user does not know the exact date they want to select (providing visual calendar context for them).
3. **Native** - sounds risky for accessibility and browser support.
4. **Free text**- Works well in all aspects when the user is likely to know the exact date and/or when only once date input is required (eg. DDMMYYYY)

**Comment by notlee** [comment]
> Is our custom one that's in Spark accessible?
> If so, can we reuse on ft.com?

I haven't tested it but we could certainly look at wrapping it, or similar third party picker, up as an Origami component if it does meet our needs.

> Is a dropdown style more accessible that a free text field, or vice versa?

No I don't think so, provided it is labelled right and grouped with a fieldset.  

>Free text- Works well in all aspects when the user is likely to know the exact date and/or when only once date input is required (eg. DDMMYYYY)

When you mention free text are you talking about the o-forms style date input with 3 text inputs for day/month/year or a single free-form text input?
Screenshot 2021-03-03 at 16 44 16

**Comment by josh-wade-ft** [comment]
> I haven't tested it but we could certainly look at wrapping it, or similar third party picker, up as an Origami component if it does meet our needs.
I think it's worth investigating, as pickers do have their place in form UX

> When you mention free text are you talking about the o-forms style date input with 3 text inputs for day/month/year or a single free-form text input?
Yes the o-forms style!

**Comment by notlee** [comment]
Moved to issue: https://github.com/Financial-Times/origami/issues/248

**Pull request closed without merging**
