### PR TITLE
feat: upgrade o3-foundtion to 2.0.0

### PR DESCRIPTION
**Pull request by frshwtr**
## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

### CODE REVIEW

**Review by notlee — CHANGES_REQUESTED** [review]
I think you'll find that the text size has increased for a bunch of components. This updates direct references in code but not where other tokens reference them. 

E.g. editorial type has tokens which reference the scale here:
https://github.com/Financial-Times/origami/blob/9dee3cf9ff13aabdbdfae4597217a4ef35e130e2/apps/dictionary/tokens/core/components/o3-editorial-typography.json#L8

Can you use visual regression testing to confirm?

**Comment by akomiqaia** [comment]
> o3.font.size.7

But this should be driven from Token studio.

> I think you'll find that the text size has increased for a bunch of components. This updates direct references in code but not where other tokens reference them.
> 
> E.g. editorial type has tokens which reference the scale here:
> 
> https://github.com/Financial-Times/origami/blob/9dee3cf9ff13aabdbdfae4597217a4ef35e130e2/apps/dictionary/tokens/core/components/o3-editorial-typography.json#L8
> 
> Can you use visual regression testing to confirm?

But this should be driven from Token Studio and current PR only updates CSS tokens for form fields that use correct font sizes based on a new scale. I updated this PR to be merged to [1804](https://github.com/Financial-Times/origami/pull/1804) pr. I believe what you are asking might be on that PR.

**Comment by frshwtr** [comment]
>  updated this PR to be merged to [1804](https://github.com/Financial-Times/origami/pull/1804) pr. I believe what you are asking might be on that PR.

This is correct, typography and editorial typography have been kept separate from this PR and is instead in #1804 , however this PR is dependent on those changes.

**Comment by notlee** [comment]
https://github.com/Financial-Times/origami/pull/1820

**Pull request closed without merging**
