### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by origamiserviceuser**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@financial-times/n-notification: 8.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-autocomplete: 1.4.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-banner: 4.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-buttons: 7.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-colors: 6.3.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-comments: 8.2.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-cookie-message: 6.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-editorial-layout: 2.2.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-editorial-typography: 2.2.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-expander: 6.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-fonts: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-footer: 9.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-footer-services: 4.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-forms: 9.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-header: 9.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-header-services: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-icons: 7.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-labels: 6.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-layout: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-loading: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-message: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-normalise: 3.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-overlay: 4.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-quote: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))

### Bug Fixes

* remove last master brand references from components ([2594662](https://www.github.com/Financial-Times/origami/commit/2594662843811d3c56cd4a50bebffe9481486e91))
</details>
<details><summary>@financial-times/o-share: 8.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))

### Bug Fixes

* remove last master brand references from components ([2594662](https://www.github.com/Financial-Times/origami/commit/2594662843811d3c56cd4a50bebffe9481486e91))
</details>
<details><summary>@financial-times/o-spacing: 3.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))

### Bug Fixes

* remove last master brand references from components ([2594662](https://www.github.com/Financial-Times/origami/commit/2594662843811d3c56cd4a50bebffe9481486e91))
</details>
<details><summary>@financial-times/o-stepped-progress: 3.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))

### Bug Fixes

* remove last master brand references from components ([2594662](https://www.github.com/Financial-Times/origami/commit/2594662843811d3c56cd4a50bebffe9481486e91))
</details>
<details><summary>@financial-times/o-subs-card: 6.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-syntax-highlight: 4.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-table: 9.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-tabs: 6.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-teaser: 6.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-teaser-collection: 4.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-toggle: 3.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-tooltip: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-topper: 5.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>
<details><summary>@financial-times/o-typography: 7.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))

### Bug Fixes

* remove last master brand references from components ([2594662](https://www.github.com/Financial-Times/origami/commit/2594662843811d3c56cd4a50bebffe9481486e91))
</details>
<details><summary>@financial-times/o-video: 7.1.0</summary>

### Features

* Rename master brand in component origami.json ([f642faf](https://www.github.com/Financial-Times/origami/commit/f642faf0574d84ea8185b56e6090c8015def27e6))
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/n-notification is at https://github.com/Financial-Times/origami/releases/tag/n-notification-v8.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-autocomplete is at https://github.com/Financial-Times/origami/releases/tag/o-autocomplete-v1.4.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-banner is at https://github.com/Financial-Times/origami/releases/tag/o-banner-v4.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-buttons is at https://github.com/Financial-Times/origami/releases/tag/o-buttons-v7.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-colors is at https://github.com/Financial-Times/origami/releases/tag/o-colors-v6.3.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-comments is at https://github.com/Financial-Times/origami/releases/tag/o-comments-v8.2.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-cookie-message is at https://github.com/Financial-Times/origami/releases/tag/o-cookie-message-v6.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-editorial-layout is at https://github.com/Financial-Times/origami/releases/tag/o-editorial-layout-v2.2.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-editorial-typography is at https://github.com/Financial-Times/origami/releases/tag/o-editorial-typography-v2.2.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-expander is at https://github.com/Financial-Times/origami/releases/tag/o-expander-v6.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-fonts is at https://github.com/Financial-Times/origami/releases/tag/o-fonts-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-footer-services is at https://github.com/Financial-Times/origami/releases/tag/o-footer-services-v4.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-forms is at https://github.com/Financial-Times/origami/releases/tag/o-forms-v9.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-header is at https://github.com/Financial-Times/origami/releases/tag/o-header-v9.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-header-services is at https://github.com/Financial-Times/origami/releases/tag/o-header-services-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-icons is at https://github.com/Financial-Times/origami/releases/tag/o-icons-v7.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-labels is at https://github.com/Financial-Times/origami/releases/tag/o-labels-v6.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-layout is at https://github.com/Financial-Times/origami/releases/tag/o-layout-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-loading is at https://github.com/Financial-Times/origami/releases/tag/o-loading-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-message is at https://github.com/Financial-Times/origami/releases/tag/o-message-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-normalise is at https://github.com/Financial-Times/origami/releases/tag/o-normalise-v3.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-quote is at https://github.com/Financial-Times/origami/releases/tag/o-quote-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-share is at https://github.com/Financial-Times/origami/releases/tag/o-share-v8.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-spacing is at https://github.com/Financial-Times/origami/releases/tag/o-spacing-v3.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-stepped-progress is at https://github.com/Financial-Times/origami/releases/tag/o-stepped-progress-v3.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-subs-card is at https://github.com/Financial-Times/origami/releases/tag/o-subs-card-v6.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-syntax-highlight is at https://github.com/Financial-Times/origami/releases/tag/o-syntax-highlight-v4.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-table is at https://github.com/Financial-Times/origami/releases/tag/o-table-v9.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-tabs is at https://github.com/Financial-Times/origami/releases/tag/o-tabs-v6.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-teaser is at https://github.com/Financial-Times/origami/releases/tag/o-teaser-v6.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-teaser-collection is at https://github.com/Financial-Times/origami/releases/tag/o-teaser-collection-v4.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-toggle is at https://github.com/Financial-Times/origami/releases/tag/o-toggle-v3.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-tooltip is at https://github.com/Financial-Times/origami/releases/tag/o-tooltip-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-topper is at https://github.com/Financial-Times/origami/releases/tag/o-topper-v5.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-typography is at https://github.com/Financial-Times/origami/releases/tag/o-typography-v7.1.0 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-video is at https://github.com/Financial-Times/origami/releases/tag/o-video-v7.1.0 :sunflower:

**Pull request merged**
