### PR TITLE
Remove most of the features of o-toggle

### PR DESCRIPTION
**Pull request by chee**
- removes visibility/display options
- removes most of the javascript (¡¡now it just toggles a single aria-attribute!!)
- removes the `callback` feature !!
- makes the css a bit smaller !!
- adds a storybook :)

it's a major because of the deleted features, [¡here's the migration guide!](https://github.com/Financial-Times/origami/blob/e205bf8ff631a92e53d06b45769f4471e94cd758/components/o-toggle/MIGRATION.md)

### CODE REVIEW

**Comment by chee** [comment]
before we merge this, let's check if anyone has a toggle button whose hidden content does not immediately follow the DOM.

**Comment by chee** [comment]
> before we merge this, let's check if anyone has a toggle button whose hidden content does not immediately follow the DOM.

done! it was! updated the code to allow that!!!!!!

**Comment by notlee** [comment]
@chee sorry I've totally forgotten where we got to with this work? Is it ready for review or did we find other usecases to consider? Oh! Was it o-header/o-footer? My instinct is to not use o-toggle as dependency

**Comment by chee** [comment]
> @chee sorry I've totally forgotten where we got to with this work? Is it ready for review or did we find other usecases to consider? Oh! Was it o-header/o-footer? My instinct is to not use o-toggle as dependency

yes, that was it. o-header and o-footer depend on it. it's nice that they fail their tests when i changed o-toggle without checking. i like the monorepo.

**Comment by notlee** [comment]
@chee please update this with a summary of your findings and screenshots of usecases etc.

**Comment by chee** [comment]
moving this conversation to #159

**Pull request closed without merging**
