### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by origamiserviceuser**
:robot: I have created a release \*beep\* \*boop\*
---
**Lee: Updated this to only release patches for the 2 footer components. Others are a lie:**

<details><summary>@financial-times/o-cookie-message: 6.4.4</summary>

### Bug Fixes

* add missing Slavery Statement & Policies to footer demos / docs ([#819](https://www.github.com/Financial-Times/origami/issues/819)) ([73bc1c6](https://www.github.com/Financial-Times/origami/commit/73bc1c6e3e75a677602fd3051c4ea9f9f72f360d))
</details>
<details><summary>@financial-times/o-footer: 9.2.3</summary>

### Bug Fixes

* add missing Slavery Statement & Policies to footer demos / docs ([#819](https://www.github.com/Financial-Times/origami/issues/819)) ([73bc1c6](https://www.github.com/Financial-Times/origami/commit/73bc1c6e3e75a677602fd3051c4ea9f9f72f360d))
</details>
<details><summary>@financial-times/o-footer-services: 4.2.4</summary>

### Bug Fixes

* add missing Slavery Statement & Policies to footer demos / docs ([#819](https://www.github.com/Financial-Times/origami/issues/819)) ([73bc1c6](https://www.github.com/Financial-Times/origami/commit/73bc1c6e3e75a677602fd3051c4ea9f9f72f360d))
</details>
<details><summary>@financial-times/o-header: 10.1.1</summary>

### Bug Fixes

* add missing Slavery Statement & Policies to footer demos / docs ([#819](https://www.github.com/Financial-Times/origami/issues/819)) ([73bc1c6](https://www.github.com/Financial-Times/origami/commit/73bc1c6e3e75a677602fd3051c4ea9f9f72f360d))
</details>
<details><summary>@financial-times/o-layout: 5.2.5</summary>

### Bug Fixes

* add missing Slavery Statement & Policies to footer demos / docs ([#819](https://www.github.com/Financial-Times/origami/issues/819)) ([73bc1c6](https://www.github.com/Financial-Times/origami/commit/73bc1c6e3e75a677602fd3051c4ea9f9f72f360d))
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:robot: Failed to create release for @financial-times/o-cookie-message :cloud:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-footer is at https://github.com/Financial-Times/origami/releases/tag/o-footer-v9.2.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-footer-services is at https://github.com/Financial-Times/origami/releases/tag/o-footer-services-v4.2.4 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Failed to create release for @financial-times/o-header :cloud:

**Comment by origamiserviceuser** [comment]
:robot: Failed to create release for @financial-times/o-layout :cloud:

**Comment by origamiserviceuser** [comment]
:robot: Failed to create release for @financial-times/o-cookie-message :cloud:

**Comment by origamiserviceuser** [comment]
:robot: Failed to create release for @financial-times/o-footer-services :cloud:

**Comment by origamiserviceuser** [comment]
:robot: Failed to create release for @financial-times/o-header :cloud:

**Comment by origamiserviceuser** [comment]
:robot: Failed to create release for @financial-times/o-layout :cloud:

**Pull request merged**
