### PR TITLE
Remove Snyk reference.

### PR DESCRIPTION
**Pull request by sentayhuJo**
## Describe your changes

- Snyk reference is detected, potentially will be detected by repo_scanner and problem will be created in problem hub. This needs to be fixed before the problem rise. 

## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)
- [ ] If it is a new feature, I have added thorough tests.
- [X] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

### CODE REVIEW

**Review by akomiqaia — APPROVED** [review]
LGTM

**Review by notlee — COMMENTED** [review]
Can we revert the changes to the blog posts without triggering Problem Hub? As blog posts they are snapshots in time, and shouldn't be edited later.

**Comment by sentayhuJo** [comment]
> Can we revert the changes to the blog posts without triggering Problem Hub? As blog posts they are snapshots in time, and shouldn't be edited later.

Sure , i will , on it now

**Comment by sentayhuJo** [comment]
Done !

**Pull request merged**
