### PR TITLE
Add proposal to remove origamiCategory from origami.json manifest

### PR DESCRIPTION
**Pull request by JakeChampion**
👋 When working on the proposal to have origami components only on npm, [chee suggested](https://financialtimes.slack.com/archives/CSW6B2VAN/p1602497687031500) that we could remove this field from the origami.json manifest as it not being used by anything. 

👉 [View the rendered proposal here](https://github.com/Financial-Times/origami/blob/origamiCategory/proposals/accepted/0000-delete-origamiCategory-manifest-field.md).

👇 leave comments and any more examples below

### CODE REVIEW

**Review by chee — APPROVED** [review]

**Comment by notlee** [comment]
I think categorising components is helpful and should be restored in the registry. They'll be even more helpful in the future when we relax the spec to make it easier to create patterns containing multiple components (that's tricky right now outside of low level components because of the class name requirement). I'd be in favour of removing this until we discuss, commit to review the categories, and restore them in the registry but think maybe it's not worth the extra work and we should keep them around for now?

**Comment by JakeChampion** [comment]
> I think categorising components is helpful and should be restored in the registry. They'll be even more helpful in the future when we relax the spec to make it easier to create patterns containing multiple components (that's tricky right now outside of low level components because of the class name requirement). I'd be in favour of removing this until we discuss, commit to review the categories, and restore them in the registry but think maybe it's not worth the extra work and we should keep them around for now?

I'm also in favour of removing the field, and if later we decide we want a similar field, we can add one :)

**Comment by notlee** [comment]
@JakeChampion Sorry, I think I was not very clear in my indirectness. I'm in favour in principle but in practise I think removing the field and adding it back is pointless work, as I think we will add it back, and therefore should leave it

**Comment by chee** [comment]
we should delete this field.

if we decide to revive it, it is not likely to use the same values.

https://github.com/Financial-Times/origami-website/issues/180

**Comment by JakeChampion** [comment]
I am not sure we would add it back. I also don't think it would be much work to remove the field and then possibly add a similar field in the future.
I like the idea of removing the field because it frees us from the already defined categories and in the future if we want a similar field, we can define all the categories that we want/need rather than being potentially hindered with the current defined categories.

For reference, posted below are our current defined categories:
>*utilities*: Sass and JavaScript utilities that provide no markup, provide no classes and are used to encapsulate shared logic between components
>*primitives*: Base components that provide minimal markup and are used by other components
>*components*: Components built from primitives and utilities, which provide markup for a complete user interface
>*layouts*: Complex components that provide styles for the whole page

**Comment by notlee** [comment]
Okay, I still think my preference would be to keep these categories and deprecate them if we add new categories in the future, but I'm happy to go with the majority here

**Pull request merged**
