### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by origamiserviceuser**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@financial-times/o-cookie-message: 6.4.1</summary>

### Bug Fixes

* remove icon for external links ([da7ea84](https://www.github.com/Financial-Times/origami/commit/da7ea8441f16db163e4459183d263cefea40e6b6))
</details>
<details><summary>@financial-times/o-footer-services: 4.2.3</summary>

### Bug Fixes

* remove icon for external links ([da7ea84](https://www.github.com/Financial-Times/origami/commit/da7ea8441f16db163e4459183d263cefea40e6b6))
</details>
<details><summary>@financial-times/o-layout: 5.2.2</summary>

### Bug Fixes

* remove icon for external links ([da7ea84](https://www.github.com/Financial-Times/origami/commit/da7ea8441f16db163e4459183d263cefea40e6b6))
</details>
<details><summary>@financial-times/o-typography: 7.3.1</summary>

### Bug Fixes

* remove icon for external links ([da7ea84](https://www.github.com/Financial-Times/origami/commit/da7ea8441f16db163e4459183d263cefea40e6b6))
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by JakeChampion — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-cookie-message is at https://github.com/Financial-Times/origami/releases/tag/o-cookie-message-v6.4.1 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-footer-services is at https://github.com/Financial-Times/origami/releases/tag/o-footer-services-v4.2.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-layout is at https://github.com/Financial-Times/origami/releases/tag/o-layout-v5.2.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-typography is at https://github.com/Financial-Times/origami/releases/tag/o-typography-v7.3.1 :sunflower:

**Pull request merged**
