### PR TITLE
fix: add missing system_code query parameter using the $system-code global variable

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Review by notlee — APPROVED** [review]

**Comment by chee** [comment]
@JakeChampion let's also take the trailing slash off here? https://github.com/Financial-Times/origami/blob/bcaf6ab39ea6df0553c1f89eca9bf6321bc6d3b9/components/o-fonts/src/scss/_variables.scss#L9

**Comment by notlee** [comment]
I think this will affect font cache / pagekit's front preloading? Perhaps the system code should be `origami` in this case.

**Comment by chee** [comment]
> I think this will affect font cache / pagekit's front preloading? Perhaps the system code should be `origami` in this case.

@Financial-Times/platforms  is this true?

**Comment by notlee** [comment]
Because each project will set its own system code I think fonts would be downloaded again moving from the front page to the article page for example?

**Comment by apaleslimghost** [comment]
yeah, that's correct. maybe we could introduce an `$o-fonts-system-code` that defaults to `$system-code` but would let us override it to (e.g.) `page-kit`?

**Pull request merged**
