### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by origamiserviceuser**
:robot: I have created a release \*beep\* \*boop\*
---
<details><summary>@financial-times/ft-concept-button: 1.1.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/n-notification: 8.2.3</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-autocomplete: 1.7.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-banner: 4.4.8</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-big-number: 3.1.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-buttons: 7.7.3</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-colors: 6.4.3</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-comments: 9.0.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-cookie-message: 6.5.1</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-editorial-layout: 2.3.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-editorial-typography: 2.3.3</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-expander: 6.2.5</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-footer: 9.2.5</summary>

### Bug Fixes

* o-footer, allow links to wrap rather than overflow with ellipses ([42bd18a](https://www.github.com/Financial-Times/origami/commit/42bd18a09fd303e2ec40b79a6909c6f91e6d9bb6))
* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-footer-services: 4.2.5</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-forms: 9.4.7</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-ft-affiliate-ribbon: 5.1.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-header: 10.1.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-header-services: 5.3.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-labels: 6.5.3</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-layout: 5.2.5</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-message: 5.4.1</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-meter: 3.2.1</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-overlay: 4.2.5</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-quote: 5.3.1</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-share: 8.3.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-social-follow: 1.0.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-spacing: 3.2.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-stepped-progress: 4.0.5</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-subs-card: 6.2.3</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-table: 9.2.7</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-tabs: 8.1.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-teaser: 6.2.4</summary>

### Bug Fixes

* o-teaser, image hero meta contrast ([6b39c4e](https://www.github.com/Financial-Times/origami/commit/6b39c4e2ef3e2765510468bd37d6ad6b26a56908))
* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-teaser-collection: 4.2.2</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-toggle: 3.2.4</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-tooltip: 5.2.5</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-topper: 5.6.4</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-typography: 7.3.3</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>
<details><summary>@financial-times/o-video: 7.2.4</summary>

### Bug Fixes

* require 3.3.0 or higher ([fc180c6](https://www.github.com/Financial-Times/origami/commit/fc180c619755daa1b7bfe65509f354cf0de113bf))
</details>

This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/ft-concept-button is at https://github.com/Financial-Times/origami/releases/tag/ft-concept-button-v1.1.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/n-notification is at https://github.com/Financial-Times/origami/releases/tag/n-notification-v8.2.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-autocomplete is at https://github.com/Financial-Times/origami/releases/tag/o-autocomplete-v1.7.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-banner is at https://github.com/Financial-Times/origami/releases/tag/o-banner-v4.4.8 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-big-number is at https://github.com/Financial-Times/origami/releases/tag/o-big-number-v3.1.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-buttons is at https://github.com/Financial-Times/origami/releases/tag/o-buttons-v7.7.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-colors is at https://github.com/Financial-Times/origami/releases/tag/o-colors-v6.4.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-comments is at https://github.com/Financial-Times/origami/releases/tag/o-comments-v9.0.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-cookie-message is at https://github.com/Financial-Times/origami/releases/tag/o-cookie-message-v6.5.1 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-editorial-layout is at https://github.com/Financial-Times/origami/releases/tag/o-editorial-layout-v2.3.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-editorial-typography is at https://github.com/Financial-Times/origami/releases/tag/o-editorial-typography-v2.3.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-expander is at https://github.com/Financial-Times/origami/releases/tag/o-expander-v6.2.5 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-footer is at https://github.com/Financial-Times/origami/releases/tag/o-footer-v9.2.5 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-forms is at https://github.com/Financial-Times/origami/releases/tag/o-forms-v9.4.7 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-ft-affiliate-ribbon is at https://github.com/Financial-Times/origami/releases/tag/o-ft-affiliate-ribbon-v5.1.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-header is at https://github.com/Financial-Times/origami/releases/tag/o-header-v10.1.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-header-services is at https://github.com/Financial-Times/origami/releases/tag/o-header-services-v5.3.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-labels is at https://github.com/Financial-Times/origami/releases/tag/o-labels-v6.5.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-layout is at https://github.com/Financial-Times/origami/releases/tag/o-layout-v5.2.5 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-message is at https://github.com/Financial-Times/origami/releases/tag/o-message-v5.4.1 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-meter is at https://github.com/Financial-Times/origami/releases/tag/o-meter-v3.2.1 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-overlay is at https://github.com/Financial-Times/origami/releases/tag/o-overlay-v4.2.5 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-quote is at https://github.com/Financial-Times/origami/releases/tag/o-quote-v5.3.1 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-share is at https://github.com/Financial-Times/origami/releases/tag/o-share-v8.3.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-social-follow is at https://github.com/Financial-Times/origami/releases/tag/o-social-follow-v1.0.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-spacing is at https://github.com/Financial-Times/origami/releases/tag/o-spacing-v3.2.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-stepped-progress is at https://github.com/Financial-Times/origami/releases/tag/o-stepped-progress-v4.0.5 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-subs-card is at https://github.com/Financial-Times/origami/releases/tag/o-subs-card-v6.2.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-table is at https://github.com/Financial-Times/origami/releases/tag/o-table-v9.2.7 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-tabs is at https://github.com/Financial-Times/origami/releases/tag/o-tabs-v8.1.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-teaser is at https://github.com/Financial-Times/origami/releases/tag/o-teaser-v6.2.4 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-teaser-collection is at https://github.com/Financial-Times/origami/releases/tag/o-teaser-collection-v4.2.2 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-toggle is at https://github.com/Financial-Times/origami/releases/tag/o-toggle-v3.2.4 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-tooltip is at https://github.com/Financial-Times/origami/releases/tag/o-tooltip-v5.2.5 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-topper is at https://github.com/Financial-Times/origami/releases/tag/o-topper-v5.6.4 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-typography is at https://github.com/Financial-Times/origami/releases/tag/o-typography-v7.3.3 :sunflower:

**Comment by origamiserviceuser** [comment]
:robot: Release for @financial-times/o-video is at https://github.com/Financial-Times/origami/releases/tag/o-video-v7.2.4 :sunflower:

**Pull request merged**
