### PR TITLE
Obt extract demo build

### PR DESCRIPTION
**Pull request by emortong**
To do:

- currently, dependencies are broken, I had to delete the package-lock.json since there were conflicts. There is a conflict needed to be resolved when running `npm install` and the `package-lock.json` needs to be recreated.
- move unit tests and integration tests to the `demo-build` folder and fix them
- delete `demo-build` files from obt
- remove unused dependencies from obt
- I added comments that start with `#402-to-do:` with questions I had. I did not know how this task would be used and what should be the input and output when running it.

### CODE REVIEW

**Comment by chee** [comment]
> - [x] currently, dependencies are broken, I had to delete the package-lock.json since there were conflicts. There is a conflict needed to be resolved when running `npm install` and the `package-lock.json` needs to be recreated.
> - [ ] move unit tests and integration tests to the `demo-build` folder and fix them
> - [x] delete `demo-build` files from obt
> - [x] remove unused dependencies from obt
> - [ ] I added comments that start with `#402-to-do:` with questions I had. I did not know how this task would be used and what should be the input and output when running it.

**Comment by JakeChampion** [comment]
[I started another pull-request](https://github.com/Financial-Times/origami/pull/477) which contains the accessibility fixes from this pull-request, I wanted to see if the issues stemmed from the demo-build changes in this pull-request and they do not.

I've made more component and component demo changes in the other pull-request, there are 7 components left, I think 4 are false positives and 1 is a potential non-issue dependant on what the design team say.

I've written up some notes about the remaining components on the pull-request -- https://github.com/Financial-Times/origami/pull/477#issuecomment-991172831

**Comment by JakeChampion** [comment]
image

**Comment by JakeChampion** [comment]
now disabling percy to not cause another 3000+ screenshots to be generated as we are only adding a newline to make o-editorial-layout pass it's tests

**Review by chee — APPROVED** [review]

**Pull request merged**
