### PR TITLE
Docs redirect 3

### PR DESCRIPTION
**Pull request by notlee**

### CODE REVIEW

**Review by chee — APPROVED** [review]
oy

**Comment by notlee** [comment]
@chee Oh let's close this. The redirect loop is gone? I thought this had been released.

**Comment by chee** [comment]
@notlee this still redirects infinitely for me https://origami.ft.com/documentation/components/

**Comment by JakeChampion** [comment]
> @notlee this still redirects infinitely for me [origami.ft.com/documentation/components](https://origami.ft.com/documentation/components/)

me too!

**Comment by notlee** [comment]
???

**Pull request merged**
