### PR TITLE
Autocomplete

### PR DESCRIPTION
**Pull request by origamiserviceuser**
From #5.

see [rendered proposal](https://github.com/Financial-Times/origami/blob/proposals/autocomplete/proposals/accepted/0000-autocomplete.md)

## comments from issue

---

**notlee** _on 2018-11-14T13:02:08_

Another example when creating a health check via biz-ops. Currently uses awesomecomplete.

screen shot 2018-11-14 at 12 59 33

---

---

**GeoffThorpeFT** _on 2019-02-22T11:21:47_

Its worth noting that an autocomplete could be connected to a static or dynamic dataset.
Static datasets (or those datasets which are rarely updated) could be connected and populated at build time (thus removing the need for a permanent connection back to the raw data at runtime). Whereas the dynamic sets would need to retain a connection to data which may only be accessible through authentication. 

---

---

**gvonkoss** _on 2019-04-12T07:35:28_

Here's an interesting UX reference of ['rules' for autocomplete](http://jeremymikkola.com/posts/2019_03_19_rules_for_autocomplete.html).

---

---

**notlee** _on 2019-04-26T10:20:40_

Looks like cloud enablement also uses an autocomplete like interface

Screenshot 2019-04-26 at 11 17 31

---

---

**notlee** _on 2019-04-26T10:21:30_

We just discussed in our open meeting and think there's definitely a strong case for this component, and it something we intend to add 🎉 

---

---

**notlee** _on 2019-09-09T09:50:39_

**Edit by @rowanmanning 2020-04-02:** The autocomplete input at the end of these tag lists are relevant, but the interface for adding multiple items to a list after selection now has a [different proposal](https://github.com/Financial-Times/origami/issues/42)

---

Another auto-complete like component but for creating tags (thanks to Jono for tracking these down a little while ago now):

TagMe:
Screenshot 2019-05-31 at 12 07 42

Graphics hub:
Screenshot 2019-05-31 at 11 47 35

Biz ops:
Screenshot 2019-05-31 at 11 58 27

Enterprise tools:
Screenshot 2019-05-31 at 11 45 32

Loadstar:
image

---

---

**adgad** _on 2020-02-07T14:47:03_

**Edit by @rowanmanning 2020-04-02:** The autocomplete input at the end of these tag lists are relevant, but the interface for adding multiple items to a list after selection now has a [different proposal](https://github.com/Financial-Times/origami/issues/42)

---

We have a use case for something similar in Spark. When search Fotoware for images, our users want to easily search for multiple combined search terms (like "Donald Trump" "Boris Johnson"), without having to use quotes or fancy syntax. In Fotoware, this is done by adding search terms as tag-like things by pressing enter. We've replicated something like that in Spark. In our case, it's not from a known set of terms, so there's no autocomplete required.

Screenshot 2020-02-07 at 14 20 11

---

---

**rowanmanning** _on 2020-04-02T11:17:17_

I've created a [new proposal](https://github.com/Financial-Times/origami/issues/42) for tag inputs. The interface for adding multiple tags _can_ use an autocomplete, but won't be built as _part_ of an autocomplete component.

---

---

**nickcolley** _on 2020-07-13T12:59:01_

I have worked on maintaining this project: https://github.com/alphagov/accessible-autocomplete

Autocomplete is very complicated to get right, my main recommendation would be to try to make sure the results are separate from the interface itself.

So you have an 'engine' like a search engine, which is responsible for taking the input data and outputting useful result data.
An example of this might be in a country picker, determining that 'GB' means Great Britain.

This 'engine' can be separated from the actual interface aspects of the component itself, and I think that way it allows you to reduce the scope of an already very complicated component.

To stretch the metaphor a bit more, it's like having a car without an engine :P

---

---

**JakeChampion** _on 2020-08-04T12:58:37_

`@remindme` to look at this before the next quarter, we need to schedule this bigger work as an OKR.

---

### CODE REVIEW

**Comment by JakeChampion** [comment]
There's also the search box on ft.com which is an autocomplete

**Comment by notlee** [comment]
Some helpful references:
- https://adamsilver.io/blog/building-an-accessible-autocomplete-control/
- https://a11ysupport.io/tech/html/datalist_element
- https://github.com/alphagov/accessible-autocomplete

**Comment by nickcolley** [comment]
https://github.com/alphagov/accessible-autocomplete/blob/master/accessibility-criteria.md <- might be useful

**Comment by JakeChampion** [comment]
We're going to do a spike and see if it is possible to use alphagov/accessible-autocomplete and wrap it into an origami component.

**Comment by notlee** [comment]
See https://github.com/Financial-Times/o-autocomplete/pull/2

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
