### PR TITLE
continued component master brand rename

### PR DESCRIPTION
**Pull request by notlee**

### CODE REVIEW

**Comment by notlee** [comment]
@Financial-Times/origami-core This is ready for review. The names of master brand demos have changes which is why Percy is unhappy. Component Sass changes happened in a previous PR so I think we're good to release this as a new baseline for Percy to compare against.

**Comment by notlee** [comment]
Let's announce the master/core rename in the newsletter and release this after (Monday?)

**Comment by notlee** [comment]
Let's announce the master/core rename in the newsletter and release this after (Monday?)

**Comment by JakeChampion** [comment]
Does https://github.com/Financial-Times/origami-registry-ui/pull/622 need to be released first?

**Review by JakeChampion — APPROVED** [review]

**Pull request merged**
