### PR TITLE
bring sass exes inside obt

### PR DESCRIPTION
**Pull request by chee**
Hopefully this will allow users of the Macintosh home computer operating system to actually complete an `npm install` in the repo

### CODE REVIEW

**Comment by JakeChampion** [comment]
It worked on my macbook!

```
❯ npm ci
npm WARN deprecated json3@3.3.0: Please use the native JSON object instead of JSON 3
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> origami@1.0.0 install
> cp hooks/* .git/hooks && cd tools/origami-build-tools && npm ci

npm WARN deprecated json3@3.3.0: Please use the native JSON object instead of JSON 3

added 1539 packages, and audited 1793 packages in 38s

200 packages are looking for funding
  run `npm fund` for details

11 vulnerabilities (7 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

added 987 packages, removed 980 packages, changed 1 package, and audited 2112 packages in 57s

276 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (4 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

~/Code/origami obtsass 57s                                                                                                                                                                                                                                                                                      05:21:46 pm
❯
```

**Comment by chee** [comment]
> It worked on my macbook!

:tada: like and subscribe!

smack that approve button it really helps!!

**Comment by notlee** [comment]
I approve :D

**Pull request merged**
